= De formation
:allow-uri-read: 


Découvrez comment déployer MySQL à partir du https://bitnami.com/stack/mysql/helm["Graphique Helm Bitnami"^]. Une fois MySQL déployé sur un cluster Kubernetes, vous pouvez gérer l'application avec Astra Control.

MySQL est une application validée pour Astra Control.

* https://docs.netapp.com/us-en/astra-control-center-2204/concepts/validated-vs-standard.html#validated-apps["Découvrez la différence entre une application validée et une application standard dans Astra Control"^].


Ces instructions s'appliquent à l'Astra Control Service et au Control Center Astra.


NOTE: Les applications déployées à partir de Google Marketplace n'ont pas été validées. Certains utilisateurs signalent des problèmes de découverte et/ou de sauvegarde avec les déploiements Google Marketplace de Postgres, MariaDB et MySQL.



== De formation

* Un groupe d'instruments qui a été ajouté à Astra Control.
+

NOTE: Pour Astra Control Center, vous pouvez d'abord ajouter le groupe d'instruments au centre de contrôle Astra ou ajouter l'application en premier.

* Versions mises à jour de Helm (version 3.2+) et Kubectl installées sur une machine locale avec le kubeconfig approprié pour le cluster




== Installez MySQL

Deux remarques importantes sur ce processus :

* Vous devez déployer votre application après l'ajout du cluster au service Astra Control, et non plus auparavant. Le centre de contrôle Astra accepte les applications avant ou après l'ajout du bloc d'instruments au centre de contrôle Astra.
* Nous vous recommandons de déployer le graphique Helm dans un namespace autre que celui par défaut.


.Étapes
. Ajoutez le repo du diagramme Bitnami :
+
[listing]
----
helm repo add bitnami https://charts.bitnami.com/bitnami
----
. Déployez MySQL avec la commande :
+
[listing]
----
helm install <name> bitnami/mysql -–namespace <namespace> --create-namespace
–-set global.storageClass=<storage_class_name>
----
+

NOTE: Si la taille du volume est modifiée, utilisez des unités de kibyte (Ki), de Mebibyte (mi) ou de Gibibyte (Gi).

+
Vous devez définir la classe de stockage uniquement dans les cas suivants :

+
** Vous utilisez Astra Control Service et vous ne souhaitez pas utiliser la classe de stockage par défaut.
** Vous utilisez Astra Control Center et vous n'avez pas encore importé le cluster dans Astra Control Center. Vous avez également importé le cluster, mais ne souhaitez pas utiliser la classe de stockage par défaut.




.Résultat
Il s'agit des éléments suivants :

* Crée un espace de noms.
* Déploie MySQL sur l'espace de noms.


Une fois les pods en ligne, vous pouvez gérer l'application avec Astra Control. Astra Control vous permet de gérer une application avec son nom, au niveau de l'espace de noms ou en utilisant une étiquette Helm.
